easy-extension:
  # 允许未知业务，默认false
  # true: 未匹配到任何业务时，走默认兜底能力的实现 (适用于平台功能体验不需要事先提供业务身份)
  # false: 匹配唯一的业务身份，未匹配或匹配多个，均会抛出异常
  # 为了提高系统健壮性，建议设为false，明确每次请求的业务身份
  allow-unknown-business: true

logging:
  level:
    # 打印每次请求匹配的业务和能力情况
    io.github.xiaoshicae.extension.core.internal.Resolver: DEBUG
